# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d5431aa9d837ecf88b732fa10ed4e0541799072fd3055bc2a383927df892988a61efcf08aff1f6b09d15b8743fc88fa96531034436d084b3ef7876de81541ec

test:
  secret_key_base: c56e3af7f4641827f37ead2a89b30415d976eef94cc90a087b5bf0eb1befbc8a79a24eea84cb80eb04cf3c1c48682116b3a86a25659db2efa14de671fe2fd407

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
